services:
  - type: web
    name: tepf-ia-facial
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libgl1 libglib2.0-0
      pip install -r requirements.txt
    startCommand: python app.py
